---
# file: nginx/defaults/main.yml
# Nginx installation and configuration

- name: Installing Nginx
  apt: name={{ item }} state=present
  with_items:
     - nginx
     - nginx-common
     - nginx-doc
     - nginx-extras

# Configuration

- name: Define default configuration for Nginx
  template: src=/templates/default.j2 dest=/etc/nginx/sites-available/default.conf

- name: Activating default website
  file: src= /etc/nginx/sites-available/default.conf dest=/etc/nginx/sites-enable/default.conf state=link
  notify: restart-nginx

