---
# MySQL Role

- name: Installing MySQL Server
  apt: name={{ item }} state=present
  with_items:
     - mysql-server-5.1
     - mysql-client-5.1
     - libmysqlclient16

- name: MySQL | set my.cnf template
  template:
    src=/roles/mysql/templates/my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root mode=0644
  notify:
  - mysql-restart

- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ root_db_password }}

- name: MySQL | Remove empty password users
  mysql_user: name='' password='' host=localhost priv=*.*:USAGE state=absent login_user=root login_password={{ root_db_password }}

- name: MySQL | Remove empty password users
  mysql_user: name='' password='' host=$ansible_fqdn priv=*.*:USAGE state=absent login_user=root login_password={{ root_db_password }}

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ root_db_password }}

